name: Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      username:
        description: "Give me your username"
        default: "citadel"
        type: "string"

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print user-provided parameter
        run: |
          echo "The username is ${{ inputs.username }}"

      - name: Print variable
        env:
          NAME: "citadel"
        run: |
          echo "Variable name is: $NAME"

# job2:
#       runs-on: ubuntu-latest
#     steps:
#     -uses: actions/checkout@v3
    
#     -name: Setup Python
#     uses: actions/setup-python@v4.1.0
  
#     -name: run a python script
#     run: python abc.py

