name: New Workflow

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install pytest
        run: pip install pytest

      - name: Run pylint
        run: |
          pylint .
        continue-on-error: true  

      - name: Run tests
        run: echo "No tests to run"   
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t citadel:ftest .
          docker push citadel:ftest
